{% set name = "hypersolver" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hypersolver-{{ version }}.tar.gz
  sha256: 9899194279375f5c117c3c1cd73eaa92c66fb47a1b31cc7bfe08d5d1b0810bd8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7
  run:
    - numpy
    - python >=3.7
    - scipy

test:
  imports:
    - hypersolver
  source_files:
    - hypersolver
  commands:
    - pip check
    - pytest
  requires:
    - pip
    - pytest

about:
  home: https://pypi.org/project/hypersolver/
  summary: hyper(bolic partial differential equations)solver
  license: MIT
  license_file:
    - license

extra:
  recipe-maintainers:
    - ngam
